config/routes.rb
require "sidekiq/web"


Rails.application.routes.draw do
  resources :gameboards
  resources :vks
  resources :inboxes
  resources :siteowners
  resources :clients
  resources :voodoo
  get 'errors/not_found'
  get 'errors/internal_server_error'
   
  devise_for :users, controllers: { registrations: 'registrations', passwords: 'users/passwords' } 
  match 'users/:id' => 'users#destroy', :via => :delete, :as => :admin_destroy_use
  root 'landing_page#index'
  resources :users do
    get :admination, on: :member
    get :deadmination, on: :member
    get :voodooation, on: :member
    get :devoodooation, on: :member
    get :clientation, on: :member
    get :declientation, on: :member
  end


  
  # get   '/кошелек/пополнить', :to=> 'siteowners#replenishment', :as => :replenishment
  # post  '/пополнение/счета', :to=> 'siteowners#payment_process', :as => :payment_process
  # get   '/платеж/не/прошел', :to=> 'siteowners#payment_fail', :as => :payment_fail
  # get   '/платеж/прошел/:secure_code', :to=> 'siteowners#payment_success', :as => :payment_success 


  resources :lists do
  	member do
  		patch :move
  	end
  end
  resources :cards do
  	member do
  		patch :move
  	end
  end
  namespace :api do
    namespace :v1 do
      get :vks, to: "vks#index"
      post :auth, to: "authentication#create"
      post :refr, to: "refresh#create"
      post :inb, to: "inboxes#create"
      post :vk, to: "vks#create"
      get :vkgrget, to: "vks#grget"
      # post :vkgrpost , to: "vks#grpost"      
      get :lobbyall, to: "users#lobbyall"
      post :vkwall, to: "vks#associate"
      post :request, to: "request#message"
      post :kill, to: "gameboards#kill"
      post :vote, to: "gameboards#vote"
      get :gameboard, to: "gameboards#index"
      get :userinfo, to: "gameboards#userinfo"
      get :vuepost, to: "vueposts#index"
      post :vuepost, to: "vueposts#create"
      post :votepost, to: "vueposts#votepost"
      get :getrait, to: "vueposts#getrait"
      get :vuepostshow, to: "vueposts#show"
      get :vuecommshow, to: "vueposts#shocomm"
      get :getPkStatus, to: "gameboards#getPkStatus"
      post :ressurect, to: "gameboards#ressurect"
      post :chat, to: "chats#create"
      get :chat, to: "chats#index"
      # post :vuepost, to: "vueposts#destroy"
      resources :vueposts
      
      resources :vks
      resources :users
      resources :locations do
        resources :recordings
      end
    end
  end
  resources :posts do
    resources :comments, module: :posts
  end
  resources :my_items  do 
    member do
      post :use_item
      patch :move
    end
  end 
  # namespace :my_items do 
  #   get :check_clan, to: "my_items#check_clan"
  # end
  get 'my_item/check_clan', to: 'my_items#check_clan'
  post 'my_items/paste_clan', to: 'my_items#paste_clan'
  # resources :discussios do
  #   resources :comments, module: :discussios
  # end
  root to: 'posts#index'
  resources :locations
  resources :discussions do
    resources :comments, module: :discussions
  end
  match "/404", :to => "errors#not_found", :via => :all
	match "/500", :to => "errors#internal_server_error", :via => :all
  Sidekiq::Web.set :session_secret, Rails.application.credentials[:secret_key_base]
  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    # Protect against timing attacks:
    # - See https://codahale.com/a-lesson-in-timing-attacks/
    # - See https://thisdata.com/blog/timing-attacks-against-string-comparison/
    # - Use & (do not use &&) so that it doesn't short circuit.
    # - Use digests to stop length information leaking (see also ActiveSupport::SecurityUtils.variable_size_secure_compare)

    login_hash = ::Digest::SHA256.hexdigest(username)
    password_hash = ::Digest::SHA256.hexdigest(password)

    ActiveSupport::SecurityUtils.secure_compare(login_hash, ::Digest::SHA256.hexdigest(Rails.application.credentials.username)) &
      ActiveSupport::SecurityUtils.secure_compare(password_hash, ::Digest::SHA256.hexdigest(Rails.application.credentials.password))
  end # if Rails.env.production?
  mount Sidekiq::Web, at: "/sidekiq"
end

app/models/discussion.rb
class Discussion < ApplicationRecord
	has_many :comments, as: :commentable
end

app/controllers/discussions/comments_controller.rb
class Discussions::CommentsController < CommentsController 
	before_action :set_commentable

 
	private
	def set_commentable
		@commentable = Discussion.find(params[:discussion_id])
	end
end

app/controllers/discussions_controller.rb
class DiscussionsController < ApplicationController
  before_action :set_discussion, only: [:show, :edit, :update, :destroy]

  # GET /discussions
  # GET /discussions.json
  def index
    @discussions = Discussion.all.order(created_at: :desc)
  end

  # GET /discussions/1
  # GET /discussions/1.json
  def show
  end

  # GET /discussions/new
  def new
    @discussion = Discussion.new
  end

  # GET /discussions/1/edit
  def edit
  end

  # POST /discussions
  # POST /discussions.json
  def create
    @discussion = Discussion.new(discussion_params)

    respond_to do |format|
      if @discussion.save
        format.html { redirect_to @discussion, notice: 'Discussion was successfully created.' }
        format.json { render :show, status: :created, location: @discussion }
      else
        format.html { render :new }
        format.json { render json: @discussion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /discussions/1
  # PATCH/PUT /discussions/1.json
  def update
    respond_to do |format|
      if @discussion.update(discussion_params)
        format.html { redirect_to @discussion, notice: 'Discussion was successfully updated.' }
        format.json { render :show, status: :ok, location: @discussion }
      else
        format.html { render :edit }
        format.json { render json: @discussion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /discussions/1
  # DELETE /discussions/1.json
  def destroy
    @discussion.destroy
    respond_to do |format|
      format.html { redirect_to discussions_url, notice: 'Discussion was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_discussion
      @discussion = Discussion.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def discussion_params
      params.require(:discussion).permit(:title)
    end
end

app/helpers/discussions_helper.rb
module DiscussionsHelper
end

app/views/discussions/_form.html.erb
<%= form_with(model: discussion, local: true) do |form| %>
  <% if discussion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(discussion.errors.count, "error") %> prohibited this discussion from being saved:</h2>

      <ul>
      <% discussion.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/discussions/edit.html.erb
<h1>Editing Discussion</h1>

<%= render 'form', discussion: @discussion %>

<%= link_to 'Show', @discussion %> |
<%= link_to 'Back', discussions_path %>

app/views/discussions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Discussions</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @discussions.each do |discussion| %>
      <tr>
        <td><%= discussion.title %></td>
        <td><%= link_to 'Show', discussion %></td>
        <td><%= link_to 'Edit', edit_discussion_path(discussion) %></td>
        <td><%= link_to 'Destroy', discussion, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Discussion', new_discussion_path %>

app/views/discussions/new.html.erb
<h1>New Discussion</h1>

<%= render 'form', discussion: @discussion %>

<%= link_to 'Back', discussions_path %>

app/views/discussions/show.html.erb
<!-- <p id="notice"><%= notice %></p> -->
<div class="mainframe">
	<p>
	  <strong>Title:</strong>
	  <%= @discussion.title %>
	</p>

	<%= link_to 'Edit', edit_discussion_path(@discussion) %> |
	<%= link_to 'Back', discussions_path %>

	<h4>комментарии:</h4>
	<div id="comments">  
		<%= render @discussion.comments.where(parent_id: nil), max_nesting: 12 %> 
		<%= render partial: "comments/form", locals: {commentable: @discussion} %>
	</div>
</div>