config/routes.rb
require "sidekiq/web"


Rails.application.routes.draw do
  resources :gameboards
  resources :vks
  resources :inboxes
  resources :siteowners
  resources :clients
  resources :voodoo
  get 'errors/not_found'
  get 'errors/internal_server_error'
   
  devise_for :users, controllers: { registrations: 'registrations', passwords: 'users/passwords' } 
  match 'users/:id' => 'users#destroy', :via => :delete, :as => :admin_destroy_use
  root 'landing_page#index'
  resources :users do
    get :admination, on: :member
    get :deadmination, on: :member
    get :voodooation, on: :member
    get :devoodooation, on: :member
    get :clientation, on: :member
    get :declientation, on: :member
  end


  
  # get   '/кошелек/пополнить', :to=> 'siteowners#replenishment', :as => :replenishment
  # post  '/пополнение/счета', :to=> 'siteowners#payment_process', :as => :payment_process
  # get   '/платеж/не/прошел', :to=> 'siteowners#payment_fail', :as => :payment_fail
  # get   '/платеж/прошел/:secure_code', :to=> 'siteowners#payment_success', :as => :payment_success 


  resources :lists do
  	member do
  		patch :move
  	end
  end
  resources :cards do
  	member do
  		patch :move
  	end
  end
  namespace :api do
    namespace :v1 do
      get :vks, to: "vks#index"
      post :auth, to: "authentication#create"
      post :refr, to: "refresh#create"
      post :inb, to: "inboxes#create"
      post :vk, to: "vks#create"
      get :vkgrget, to: "vks#grget"
      # post :vkgrpost , to: "vks#grpost"      
      get :lobbyall, to: "users#lobbyall"
      post :vkwall, to: "vks#associate"
      post :request, to: "request#message"
      post :kill, to: "gameboards#kill"
      post :vote, to: "gameboards#vote"
      get :gameboard, to: "gameboards#index"
      get :userinfo, to: "gameboards#userinfo"
      get :vuepost, to: "vueposts#index"
      post :vuepost, to: "vueposts#create"
      post :votepost, to: "vueposts#votepost"
      get :getrait, to: "vueposts#getrait"
      get :vuepostshow, to: "vueposts#show"
      get :vuecommshow, to: "vueposts#shocomm"
      get :getPkStatus, to: "gameboards#getPkStatus"
      post :ressurect, to: "gameboards#ressurect"
      post :chat, to: "chats#create"
      get :chat, to: "chats#index"
      # post :vuepost, to: "vueposts#destroy"
      resources :vueposts
      
      resources :vks
      resources :users
      resources :locations do
        resources :recordings
      end
    end
  end
  resources :posts do
    resources :comments, module: :posts
  end
  resources :my_items  do 
    member do
      post :use_item
      patch :move
    end
  end 
  # namespace :my_items do 
  #   get :check_clan, to: "my_items#check_clan"
  # end
  get 'my_item/check_clan', to: 'my_items#check_clan'
  post 'my_items/paste_clan', to: 'my_items#paste_clan'
  # resources :discussios do
  #   resources :comments, module: :discussios
  # end
  root to: 'posts#index'
  resources :locations
  resources :discussions do
    resources :comments, module: :discussions
  end
  match "/404", :to => "errors#not_found", :via => :all
	match "/500", :to => "errors#internal_server_error", :via => :all
  Sidekiq::Web.set :session_secret, Rails.application.credentials[:secret_key_base]
  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    # Protect against timing attacks:
    # - See https://codahale.com/a-lesson-in-timing-attacks/
    # - See https://thisdata.com/blog/timing-attacks-against-string-comparison/
    # - Use & (do not use &&) so that it doesn't short circuit.
    # - Use digests to stop length information leaking (see also ActiveSupport::SecurityUtils.variable_size_secure_compare)

    login_hash = ::Digest::SHA256.hexdigest(username)
    password_hash = ::Digest::SHA256.hexdigest(password)

    ActiveSupport::SecurityUtils.secure_compare(login_hash, ::Digest::SHA256.hexdigest(Rails.application.credentials.username)) &
      ActiveSupport::SecurityUtils.secure_compare(password_hash, ::Digest::SHA256.hexdigest(Rails.application.credentials.password))
  end # if Rails.env.production?
  mount Sidekiq::Web, at: "/sidekiq"
end

app/models/card.rb
class Card < ApplicationRecord
	acts_as_list scope: :list
  belongs_to :list
  validates :name, presence: true
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_card, only: [:show, :edit, :update, :destroy, :move]

  # GET /cards
  # GET /cards.json
  def index
    @cards = Card.all
  end

  # GET /cards/1
  # GET /cards/1.json
  def show
  end

  # GET /cards/new
  def new
    @card = Card.new
  end

  # GET /cards/1/edit
  def edit
  end

  # POST /cards
  # POST /cards.json
  def create
    @card = Card.new(card_params)

    respond_to do |format|
      if @card.save
        format.html { redirect_to @card, notice: 'Card was successfully created.' }
        format.json { render :show, status: :created, location: @card }
      else
        format.html { render :new }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cards/1
  # PATCH/PUT /cards/1.json
  def update
    respond_to do |format|
      if @card.update(card_params)
        format.html { redirect_to @card, notice: 'Card was successfully updated.' }
        format.json { render :show, status: :ok, location: @card }
      else
        format.html { render :edit }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cards/1
  # DELETE /cards/1.json
  def destroy
    @card.destroy
    respond_to do |format|
      format.html { redirect_to cards_url, notice: 'Card was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def move
    @card.update(card_params)
    render action: :show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_card
      @card = Card.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def card_params
      params.require(:card).permit(:list_id, :name, :position)
    end
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/_form.html.erb
<%= form_with(model: card, local: true) do |form| %>
  <% if card.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(card.errors.count, "error") %> prohibited this card from being saved:</h2>

      <ul>
      <% card.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :list_id %>
    <%= form.text_field :list_id %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :position %>
    <%= form.number_field :position %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cards/edit.html.erb
<h1>Editing Card</h1>

<%= render 'form', card: @card %>

<%= link_to 'Show', @card %> |
<%= link_to 'Back', cards_path %>

app/views/cards/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cards</h1>

<table>
  <thead>
    <tr>
      <th>List</th>
      <th>Name</th>
      <th>Position</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cards.each do |card| %>
      <tr>
        <td><%= card.list %></td>
        <td><%= card.name %></td>
        <td><%= card.position %></td>
        <td><%= link_to 'Show', card %></td>
        <td><%= link_to 'Edit', edit_card_path(card) %></td>
        <td><%= link_to 'Destroy', card, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Card', new_card_path %>

app/views/cards/new.html.erb
<h1>New Card</h1>

<%= render 'form', card: @card %>

<%= link_to 'Back', cards_path %>

app/views/cards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>List:</strong>
  <%= @card.list %>
</p>

<p>
  <strong>Name:</strong>
  <%= @card.name %>
</p>

<p>
  <strong>Position:</strong>
  <%= @card.position %>
</p>

<%= link_to 'Edit', edit_card_path(@card) %> |
<%= link_to 'Back', cards_path %>