config/routes.rb
require "sidekiq/web"


Rails.application.routes.draw do
  resources :gameboards
  resources :vks
  resources :inboxes
  resources :siteowners
  resources :clients
  resources :voodoo
  get 'errors/not_found'
  get 'errors/internal_server_error'
   
  devise_for :users, controllers: { registrations: 'registrations', passwords: 'users/passwords' } 
  match 'users/:id' => 'users#destroy', :via => :delete, :as => :admin_destroy_use
  root 'landing_page#index'
  resources :users do
    get :admination, on: :member
    get :deadmination, on: :member
    get :voodooation, on: :member
    get :devoodooation, on: :member
    get :clientation, on: :member
    get :declientation, on: :member
  end


  
  # get   '/кошелек/пополнить', :to=> 'siteowners#replenishment', :as => :replenishment
  # post  '/пополнение/счета', :to=> 'siteowners#payment_process', :as => :payment_process
  # get   '/платеж/не/прошел', :to=> 'siteowners#payment_fail', :as => :payment_fail
  # get   '/платеж/прошел/:secure_code', :to=> 'siteowners#payment_success', :as => :payment_success 


  resources :lists do
  	member do
  		patch :move
  	end
  end
  resources :cards do
  	member do
  		patch :move
  	end
  end
  namespace :api do
    namespace :v1 do
      get :vks, to: "vks#index"
      post :auth, to: "authentication#create"
      post :refr, to: "refresh#create"
      post :inb, to: "inboxes#create"
      post :vk, to: "vks#create"
      get :vkgrget, to: "vks#grget"
      # post :vkgrpost , to: "vks#grpost"      
      get :lobbyall, to: "users#lobbyall"
      post :vkwall, to: "vks#associate"
      post :request, to: "request#message"
      post :kill, to: "gameboards#kill"
      post :vote, to: "gameboards#vote"
      get :gameboard, to: "gameboards#index"
      get :userinfo, to: "gameboards#userinfo"
      get :vuepost, to: "vueposts#index"
      post :vuepost, to: "vueposts#create"
      post :votepost, to: "vueposts#votepost"
      get :getrait, to: "vueposts#getrait"
      get :vuepostshow, to: "vueposts#show"
      get :vuecommshow, to: "vueposts#shocomm"
      get :getPkStatus, to: "gameboards#getPkStatus"
      post :ressurect, to: "gameboards#ressurect"
      post :chat, to: "chats#create"
      get :chat, to: "chats#index"
      # post :vuepost, to: "vueposts#destroy"
      resources :vueposts
      
      resources :vks
      resources :users
      resources :locations do
        resources :recordings
      end
    end
  end
  resources :posts do
    resources :comments, module: :posts
  end
  resources :my_items  do 
    member do
      post :use_item
      patch :move
    end
  end 
  # namespace :my_items do 
  #   get :check_clan, to: "my_items#check_clan"
  # end
  get 'my_item/check_clan', to: 'my_items#check_clan'
  post 'my_items/paste_clan', to: 'my_items#paste_clan'
  # resources :discussios do
  #   resources :comments, module: :discussios
  # end
  root to: 'posts#index'
  resources :locations
  resources :discussions do
    resources :comments, module: :discussions
  end
  match "/404", :to => "errors#not_found", :via => :all
	match "/500", :to => "errors#internal_server_error", :via => :all
  Sidekiq::Web.set :session_secret, Rails.application.credentials[:secret_key_base]
  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    # Protect against timing attacks:
    # - See https://codahale.com/a-lesson-in-timing-attacks/
    # - See https://thisdata.com/blog/timing-attacks-against-string-comparison/
    # - Use & (do not use &&) so that it doesn't short circuit.
    # - Use digests to stop length information leaking (see also ActiveSupport::SecurityUtils.variable_size_secure_compare)

    login_hash = ::Digest::SHA256.hexdigest(username)
    password_hash = ::Digest::SHA256.hexdigest(password)

    ActiveSupport::SecurityUtils.secure_compare(login_hash, ::Digest::SHA256.hexdigest(Rails.application.credentials.username)) &
      ActiveSupport::SecurityUtils.secure_compare(password_hash, ::Digest::SHA256.hexdigest(Rails.application.credentials.password))
  end # if Rails.env.production?
  mount Sidekiq::Web, at: "/sidekiq"
end

app/models/post.rb
class Post < ApplicationRecord
	has_many :comments, :as => :commentable, :dependent => :delete_all
	belongs_to :user
	has_many :votes, as: :voteable
end

app/controllers/posts/comments_controller.rb
class Posts::CommentsController < CommentsController 
    before_action :set_commentable
    private
    def set_commentable
        @commentable = Post.find(params[:post_id])
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    # logic in landing_page controller o_O
    # @posts = Post.all.order(created_at: :desc)
    # @vks = Vk.where('raiting > 10.00').order(created_at: :desc, medias_row: :desc,  raiting: :desc, v_like: :desc).limit(500)
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user = current_user

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to '/', notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body, :clan_name)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    Тема поста: <br>
    <%= form.text_field :title %>
    <%= form.hidden_field 'clan_name', :value => current_user.role %>
  </div>
  пост: <br>
  <div class="field">

    <%= form.text_area :body, cols: "50", rows: "6" %>
  </div>

  <div class="actions">
    <%= form.submit "Сохранить", :class => "el-button el-button--mini" %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<div class="lostcenter">
	<div class="mainframepaddings">
		<h1>Редактировать пост</h1>

		<%= render 'form', post: @post %>

		<%= link_to 'Посмотреть', @post %> |
		<%= link_to 'Назад', '/' %>
	</div>
</div>

app/views/posts/index.html.erb
<div class="mainframe lostcenter">

</div>
 

app/views/posts/new.html.erb
<div class="lostcenter">
	<div class="mainframepaddings aprior">
		<%= render 'form', post: @post %>
		<%= link_to 'Назад', '/' %>
	</div>
</div>
 

app/views/posts/show.html.erb
<!-- <p id="notice"><%= notice %></p> -->
<div class="lostcenter">
	<div class="mainframepaddings">
	  <h3><%= @post.title %></h3>
		<div class="mediumtext">
	  	<%=simple_format  @post.body %>
	  </div>
		<div class="aprior" style="padding-bottom: 0.4em">
		<%#= link_to 'редактировать', edit_post_path(@post) %> <!--  | -->
		<%= link_to 'назад', 'javascript:history.back()' %>		
		</div>
 
		<h4 class="comm">комментарии:</h4>
		<div id="comments" class="mediumtext"> 
			<%= render @post.comments.where(parent_id: nil), max_nesting: 24 %> 
			<%= render partial: "comments/form", locals: {commentable: @post} %>
		</div>
	</div>
</div>